# Server
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/jobsearch
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=job-search-group
spring.kafka.consumer.auto-offset-reset=earliest

# JWT
jwt.secret=mySecretKeyForJWTTokenGenerationMustBe256BitsLongAtLeast1234567890AbCdEf
jwt.expiration=86400000

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Logging
logging.level.com.jobsearch=DEBUG
${RAPIDAPI_KEY}
notification.email=YOUREMAIL@gmail.com
sendgrid.api.key=your_sendgrid_key_here
adzuna.app.id=${ADZUNA_APP_ID}
adzuna.app.key=9d892bf82bca5ec675feb1338130c172
logging.level.org.springframework.security=WARN
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
openrouter.api.key=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

# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bhavishyay382@gmail.com
spring.mail.password=bikd ukdz qpnl tizt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
